### ISSUE TITLE
Unable to install from NuGet

### ISSUE THREAD

**Issue by hanggrian** [matarillo/dcsoup#1]
I get error message `Package restore failed. Rolling back package changes for 'app name'.` when attempting to install from NuGet. Being new in C# and .Net development, I don't know what other information I should provide here. I'm building Windows Universal App with latest Windows 10 SDK.

**Comment by matarillo** [comment]
Hi hendraanggrian,

Thank you for the report.

I'm afraid that current version of dcsoup (v0.2.0) does not support Universal Windows Platform. A future version of dcsoup may support UWP, but if you urgently need it and cannot wait for the next version, please concider alternatives such as [AngleSharp](https://www.nuget.org/packages/AngleSharp/).

**Comment by hanggrian** [comment]
@matarillo alright I appreciate the explanation and I thank you for the alternative suggestion. You may close this now.

**Comment by matarillo** [comment]
Recently I released dcsoup v1.0.0 which supports .NET Standard 1.3.  I think that AngleSharp is better than dcsoup in most cases, but if you like dcsoup, hope you have a try.
