### ISSUE TITLE
HTTP status

### ISSUE THREAD

**Issue by Canejo** [matarillo/dcsoup#2]
Is it possible to retrieve the http status?
[List of HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)

**Comment by matarillo** [comment]
In fact, dcsoup itself doesn't have a capability of HTTP client and it just provides a convinient extension method which depends on System.Net.Http.HttpClient.
How about checking HttpResponseMessage.StatusCode property?

```cs
async void SampleMethod(Uri url)
{
    var client = new HttpClient();
    var message = await client.GetAsync(url);
    var status = message.StatusCode;
    if (status == HttpStatusCode.OK)
    {
        var document = message.Parse();
        // do your work
    }
}
```
