### ISSUE TITLE
Size() does not exist in Elements

### ISSUE THREAD

**Issue by chitgoks** [matarillo/dcsoup#3]
Size() does not exist in Elements

**Comment by matarillo** [comment]
How about Elements.Count property instead?

**Comment by chitgoks** [comment]
Hi. there is none. NSoup has the Count property so I am using that now.

**Comment by matarillo** [comment]
Could you share a minimal code example which can reproduce the issue, and your environment? (.NET/.NET Core/Mono/etc, Version, OS)

**Comment by chitgoks** [comment]
hi
my environment is visual studio 2012, windows 7, .net 45 and dc soup v1.0.0

**Comment by matarillo** [comment]
Thank you. It would be helpful if you share a small code example.

**Comment by chitgoks** [comment]
hi. when i selected something like this

`Elements asElems = doc.Select("a");`

asElems.Count .Length .Size does not exist.

**Comment by matarillo** [comment]
I can't reproduce the issue... (VS2017, Win10, .NET4.5, dcsoup 1.0.0)
![image](https://user-images.githubusercontent.com/144277/29862992-2182e50a-8d23-11e7-9dd3-4a24af4589df.png)

**Comment by chitgoks** [comment]
this is odd. i must have overlooked it. apologies.
