### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by atifaziz** [matarillo/dcsoup#4]
In [a comment](https://github.com/matarillo/dcsoup/issues/1) in issue #1, @matarillo said:

>  I think that AngleSharp is better than dcsoup in most cases

Could you comment further on that? Why or how do you think AngleSharp is better? Suppose it is, does that mean you don't expect to maintain or develop dcsoup further? I'm also curious, since AngleSharp existed before dcsoup, why did you implement dcsoup at all? I'm asking these questions to evaluate risks involved with long-term reliance on dcsoup. In other words, does this project risk end up being [no longer maintained like NSoup](https://github.com/GeReV/NSoup/commit/e34251676eaca7aa42237bf607b104916e755b5f#diff-04c6e90faac2675aa89e2176d2eec7d8R1)?

**Comment by matarillo** [comment]
This project is hardly maintained. It is a fun project of mine and I don't have any plan or roadmap to update dcsoup so far. If someone creates a clear and specific issue to ask for a new feature or a bug fix, I will probably try to solve it in my free time. But I can't guarantee either my long-term commitment nor my continuous maintenance.  Thank you for your understanding.

**Comment by atifaziz** [comment]
@matarillo I understand and thanks for laying it out clearly.
