### ISSUE TITLE
Feature Request: .NET Standard 2.0 support

### ISSUE THREAD

**Issue by ghost** [matarillo/dcsoup#5]
Could you update dcsoup for .NET Standard 2.0 support?

Thanks much 👍

**Comment by matarillo** [comment]
Thank you for your feedback.
My understanding is that every platform that supports .NET standard 2.0 also supports .NET standard 1.3 at the same time, so if your program is on a platform such as .NET Core >=2.0, .NET framework >=4.6.1, and Mono >=5.4, you can use dcsoup as it is.
https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

Do you have any special needs that require dcsoup to be upgraded to .NET standard 2.0?

**Comment by ghost** [comment]
>> My understanding is that every platform that supports .NET standard 2.0 also supports .NET standard 1.3 at the same time, so if your program is on a platform such as .NET Core >=2.0, .NET framework >=4.6.1, and Mono >=5.4, you can use dcsoup as it is.
https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

Oh okay. Cool. 

Got a totally unrelated question. Where can I find the API documentation? Cos I tried looking at the attached documentation file and it didn't help much.

**Comment by matarillo** [comment]
I made the API documentation site.
[Have a look at it](https://matarillo.github.io/dcsoup/api/index.html).

**Comment by ghost** [comment]
> I made the API documentation site.
Have a look at it.

Thanks! I'll take a look at it later.
